CSVdata/urls.py
from django.urls import path

from . import views

app_name = 'CSVdata'

urlpatterns = [
    path('', views.csvList, name='Home'),
    path('<int:file_id>', views.CSVView, name='View'),
    path('<int:file_id>/dashboard', views.dashboard, name='Dashboard'),
    path('upload', views.upload, name='Upload'),
]

devsites/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application 
urlpatterns += [
    path('CSVdata/', include('CSVdata.urls', namespace='CSVdata')),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

CSVdata/models.py
from django.db import models

class CSVFile(models.Model):
    file_name = models.CharField(max_length=500)
    file_path = models.FileField(upload_to='%Y/%m/%d', null=True, verbose_name='')
    file_dateadded = models.DateField('Date Added', 'Date Added', True)

    def __str__(self):
        return self.file_name + ": " + str(self.file_path)

polls/models.py
from django.db import models

# Create your models here.

CSVdata/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import CSVFile
from .fileForm import FileForm

import pandas as pd
import numpy as np

# Create your views here.
def csvList(request):
    latest_file_list = CSVFile.objects.all()
    context = {'current_file_list': latest_file_list}
    return render(request, 'csvdata/index.html', context)

def dashboard(request, file_id):    
    # Return the file Details
    fileRep = CSVFile.objects.get(pk=file_id)
    context = {'csvFile': fileRep}

    data = pd.read_csv(fileRep.file_path, iterator=True, chunksize=20000)
    df = pd.concat(data, ignore_index=True)
    df["state"].replace({np.NaN: "BLANK"}, inplace = True) 

    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    listGroups = list(df.groupby([df['date'].dt.year]).groups.keys())
    dfGBCount = df.groupby([df['date'].dt.year]).agg({'count'})[['date']]
    npReport = dfGBCount.to_numpy()

    listReport = npReport.tolist()

    context= {
              'fileid': file_id,
              'filepath': fileRep.file_path,
              'filename': fileRep.file_name,
              'list_data': listReport,
              'list_groups': listGroups,
              }    

    return render(request, 'csvdata/dashboard.html', context)

def CSVView(request, file_id):
    # Return the file Details
    fileRep = CSVFile.objects.get(pk=file_id)
    context = {'csvFile': fileRep}

    data = pd.read_csv(fileRep.file_path, iterator=True, chunksize=20000)
    df = pd.concat(data, ignore_index=True)
    df["state"].replace({np.NaN: "BLANK"}, inplace = True) 
    data_html = df.to_html()

    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    listGroups = list(df.groupby([df['date'].dt.year]).groups.keys())
    dfGBCount = df.groupby([df['date'].dt.year]).agg({'count'})[['date']]
    npReport = dfGBCount.to_numpy()

    listReport = npReport.tolist()

    report_html = dfGBCount.to_html()

    context= {
              'fileid': file_id,
              'filepath': fileRep.file_path,
              'filename': fileRep.file_name,
              'loaded_data': data_html,
              'report_data': report_html,
              'list_data': listReport,
              'list_groups': listGroups,
              }    

    return render(request, 'csvdata/view.html', context)

def upload(request):

    lastfile= CSVFile.objects.last()

    filepath = lastfile.file_path

    filename = lastfile.file_name

    form= FileForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('csvdata:Home'))
    else:
        form = FileForm()
            
    context= {
              'filepath': filepath,
              'form': form,
              'filename': filename,
              }    
      
    return render(request, 'csvdata/upload.html', context)

polls/views.py
from django.shortcuts import render

# Create your views here.

CSVdata/templates/CSVdata/dashboard.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'csvdata/csvcss.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<body>
    <nav class="body-col-1">
        <ul class="navList">
            <li>
                <a class="" href="/CSVdata/">Files</a>
            </li>
            <li>
                <a class="" href="/CSVdata/upload">Upload</a>
            </li>
        </ul>
    </nav>
    <div class="body-col-2">
        <header>CSV File: {{ filename }}</header>
        <main class="fileContent">
            <div id="container" style="width: 100%; min-width: 310px; height: 400px; margin: 0 auto; flex-basis: 100%;" class="border"></div>
        </main>
        <footer></footer>
    </div>
</body>

<script>
      _categories = {{list_groups|safe}};
      _values = {{list_data|safe}};

      Highcharts.chart('container', {
	  chart: {
              type: 'column'
	  },
	  title: {
              text: 'Entities with same Year'
	  },
	  subtitle: {
              text: ')'
	  },
	  xAxis: {
              categories:_categories,
              crosshair: true
	  },
	  yAxis: {
              min: 0,
              title: {
		  text: ''
              }
	  },
	  tooltip: {
              headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
              pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
		  '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
              footerFormat: '</table>',
              shared: true,
              useHTML: true
	  },
          plotOptions: {
              pie: {
                  size: '100%',
                  height: '100%',
                  dataLabels: {
                      enabled: false
                  }
              },
              column: {
		  pointPadding: 0.2,
		  borderWidth: 0
        }
	  },
	  series: [{
              name: '# Count',
              data: _values

	  }]
      });
</script>

CSVdata/templates/CSVdata/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'csvdata/csvcss.css' %}">

<body>
    <nav class="body-col-1">
        <div>
            <a class="menuitem" href="/CSVdata/upload">Upload</a>
        </div>
    </nav>
    <div class="body-col-2">
        <header>CSV Data Files</header>
        <main class="fileContent">
            {% if current_file_list %}
            <div id="results">
                <ul class="csvList">
                    {% for csvFile in current_file_list %}
                    <li><img src="{% static 'csvdata/msxlsicon.ico' %}" /><a href="{% url 'CSVdata:View' csvFile.id %}">{{ csvFile.file_name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            {% else %}
            <p>No files have been posted.</p>
            {% endif %}
        </main>
        <footer></footer>
    </div>
</body>

CSVdata/templates/CSVdata/upload.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'csvdata/csvcss.css' %}">

<body>
    <nav class="body-col-1">
        <div>
            <a class="" href="/CSVdata/">Files</a>
        </div>
    </nav>
    <div class="body-col-2">
        <header>Upload CSV Files</header>
        <main class="fileContent">
            <form enctype="multipart/form-data" method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" value="Upload" />
            </form>
            <article>
                {{loaded_data | safe}}
            </article>
        </main>
        <footer></footer>
    </div>
</body>

CSVdata/templates/CSVdata/view.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'csvdata/csvcss.css' %}">

<body>
    <nav class="body-col-1">
        <ul class="navList">
            <li>
                <a class="" href="/CSVdata/">Files</a>
            </li>
            <li>
                <a class="" href="/CSVdata/upload">Upload</a>
            </li>
        </ul>
    </nav>
    <div class="body-col-2">
        <header>CSV File: {{ filename }}</header>
        <div class="reports">
            <a class="" href="{{ fileid }}/dashboard">Dashboard</a>
        </div>
        <main class="fileContent">
            {{loaded_data | safe}}
        </main>
        <footer></footer>
    </div>
</body>